// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20241017205059_AddProductImageEntity")]
    partial class AddProductImageEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UK_Categories_Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 371, DateTimeKind.Utc).AddTicks(2695),
                            Description = "Bu kategori giysiler içerir.",
                            ImageUrl = "https://cdn.myikas.com/images/6d452771-fa42-482d-a9a5-b47e65a5bf47/f7875799-b576-4294-930a-198ec803046e/1080/t-shirt-black-a.jpg",
                            Name = "Giyim"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmailAuthenticator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActivationKey");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IsVerified");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailAuthenticators", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UK_OperationClaims_Name")
                        .IsUnique();

                    b.ToTable("OperationClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(3692),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4408),
                            Name = "Users.Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4420),
                            Name = "Users.Write"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4424),
                            Name = "Users.Read"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4430),
                            Name = "Users.Create"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4439),
                            Name = "Users.Update"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4443),
                            Name = "Users.Delete"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4540),
                            Name = "UserOperationClaims.Admin"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4546),
                            Name = "UserOperationClaims.Write"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4552),
                            Name = "UserOperationClaims.Read"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4557),
                            Name = "UserOperationClaims.Create"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4561),
                            Name = "UserOperationClaims.Update"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4565),
                            Name = "UserOperationClaims.Delete"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4644),
                            Name = "Products.Admin"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4649),
                            Name = "Products.Write"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4654),
                            Name = "Products.Read"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4658),
                            Name = "Products.Create"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4665),
                            Name = "Products.Update"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4669),
                            Name = "Products.Delete"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4744),
                            Name = "ProductImages.Admin"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4748),
                            Name = "ProductImages.Write"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4753),
                            Name = "ProductImages.Read"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4758),
                            Name = "ProductImages.CreateBulk"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4805),
                            Name = "ProductImages.Delete"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4882),
                            Name = "OperationClaims.Admin"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4887),
                            Name = "OperationClaims.Write"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4891),
                            Name = "OperationClaims.Read"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4952),
                            Name = "OperationClaims.Create"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4958),
                            Name = "OperationClaims.Update"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(4963),
                            Name = "OperationClaims.Delete"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5040),
                            Name = "Categories.Admin"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5045),
                            Name = "Categories.Write"
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5049),
                            Name = "Categories.Read"
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5056),
                            Name = "Categories.Create"
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5061),
                            Name = "Categories.Update"
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5065),
                            Name = "Categories.Delete"
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5136),
                            Name = "Auth.Admin"
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5141),
                            Name = "Auth.Write"
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5145),
                            Name = "Auth.Read"
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 372, DateTimeKind.Utc).AddTicks(5149),
                            Name = "Auth.RevokeToken"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OtpAuthenticator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IsVerified");

                    b.Property<byte[]>("SecretKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("SecretKey");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpAuthenticators", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("UnitPrice");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Name" }, "UK_Products_Name")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 373, DateTimeKind.Utc).AddTicks(7568),
                            Description = "This device is able to destroy asteroids.",
                            Name = "Asteroid Destroyer",
                            UnitPrice = 50000000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 373, DateTimeKind.Utc).AddTicks(7588),
                            Description = "",
                            Name = "Mavi Ekose Gömlek",
                            UnitPrice = 900.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Url = "https://i.pinimg.com/originals/99/86/ab/9986ab7d3cee03f5949c9587938bb5c4.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Url = "https://t4.ftcdn.net/jpg/07/46/18/01/360_F_746180145_5A7i83iHIGbKBXb2ArfZeN0BDLwOiW4g.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Url = "https://004406.cdn.akinoncloud.com/products/2020/06/11/96244/61c41c8f-a14d-4575-8ccb-52855c7994b5_size350x525_quality90_cropCenter.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Url = "https://004406.a-cdn.akinoncloud.com/products/2024/02/29/595907/2230e9c3-4c05-4812-86a9-0fb428cc6ef1_size555x830_quality90_cropCenter.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Url = "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/56971/uploads/urunresimleri/buyuk/koyu-mavi-uzun-kollu-ekoseli-cepli-gar--529e-.jpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByIp");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expires");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReasonRevoked");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReplacedByToken");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RevokedByIp");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Token");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthenticatorType")
                        .HasColumnType("int")
                        .HasColumnName("AuthenticatorType");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UK_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthenticatorType = 0,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 377, DateTimeKind.Utc).AddTicks(7429),
                            Email = "narch@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = new byte[] { 210, 209, 217, 183, 240, 124, 25, 62, 113, 14, 225, 8, 20, 109, 44, 94, 22, 41, 15, 231, 91, 29, 199, 242, 167, 248, 138, 100, 88, 100, 197, 81, 246, 41, 157, 24, 229, 200, 130, 191, 71, 70, 28, 87, 174, 13, 208, 208, 141, 28, 103, 46, 243, 236, 38, 194, 167, 115, 121, 193, 197, 81, 76, 198 },
                            PasswordSalt = new byte[] { 13, 250, 231, 240, 125, 18, 46, 81, 24, 23, 117, 157, 91, 179, 187, 156, 168, 49, 150, 53, 152, 23, 193, 184, 65, 185, 6, 232, 216, 18, 226, 131, 163, 147, 210, 201, 70, 132, 226, 209, 101, 226, 100, 84, 252, 202, 182, 176, 195, 76, 143, 193, 164, 252, 86, 165, 181, 79, 136, 22, 178, 225, 66, 132, 115, 1, 129, 14, 94, 169, 144, 60, 15, 135, 76, 82, 21, 69, 209, 1, 210, 176, 11, 32, 188, 172, 38, 56, 94, 180, 227, 76, 79, 218, 173, 157, 235, 69, 239, 222, 37, 51, 19, 110, 251, 27, 244, 229, 7, 135, 6, 208, 58, 138, 248, 205, 92, 121, 229, 55, 75, 116, 244, 16, 171, 197, 246, 105 }
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OperationClaimId");

                    b.HasIndex(new[] { "UserId", "OperationClaimId" }, "UK_UserOperationClaims_UserId_OperationClaimId")
                        .IsUnique();

                    b.ToTable("UserOperationClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 17, 20, 50, 58, 378, DateTimeKind.Utc).AddTicks(9510),
                            OperationClaimId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmailAuthenticator", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("EmailAuthenticators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OtpAuthenticator", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("OtpAuthenticators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserOperationClaim", b =>
                {
                    b.HasOne("Domain.Entities.OperationClaim", "OperationClaim")
                        .WithMany("UserOperationClaims")
                        .HasForeignKey("OperationClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserOperationClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationClaim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.OperationClaim", b =>
                {
                    b.Navigation("UserOperationClaims");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("EmailAuthenticators");

                    b.Navigation("OtpAuthenticators");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserOperationClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
